/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/schema.json
export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  noindex?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type InlineImage = {
  _type: "inlineImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  caption?: string;
};

export type Cta = {
  _type: "cta";
  label: string;
  target: "erstgespraech" | "pakete" | "url";
  url?: string;
};

export type Callout = {
  _type: "callout";
  tone: "hinweis" | "tipp";
  text: SimpleBlockContent;
};

export type SimpleBlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: Array<{
    href: string;
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href: string;
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & InlineImage)
  | ({
      _key: string;
    } & Callout)
  | ({
      _key: string;
    } & Cta)
>;

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  phone: string;
  email: string;
  responseNote?: string;
  bookingUrl?: string;
  linkedin?: string;
  instagram?: string;
  defaultSeo?: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: string;
  answer: SimpleBlockContent;
  topic: "pakete" | "plattform" | "clubprozesse" | "wachstum" | "allgemein";
  order?: number;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  category: CategoryReference;
  author: AuthorReference;
  publishedAt: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  body: BlockContent;
  related?: Array<
    {
      _key: string;
    } & PostReference
  >;
  seo?: Seo;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  role: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio: string;
  linkedin?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description: string;
  audience: "einsteiger" | "mitgliedschaft" | "gaeste" | "unternehmen" | "clubbetrieb";
  order?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Seo
  | SanityImageAssetReference
  | InlineImage
  | Cta
  | Callout
  | SimpleBlockContent
  | BlockContent
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | Faq
  | CategoryReference
  | AuthorReference
  | PostReference
  | Post
  | Author
  | Slug
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/sanity/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current) && (!defined($rubrik) || category->slug.current == $rubrik)]    | order(publishedAt desc) {  _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  mainImage{alt, asset->{_id, url, metadata{lqip, dimensions}}},  category->{title, "slug": slug.current, audience},  author->{name, "slug": slug.current, image{alt, asset->{_id, url, metadata{lqip}}}}}
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  mainImage: {
    alt: string | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  category: {
    title: string;
    slug: string;
    audience: "clubbetrieb" | "einsteiger" | "gaeste" | "mitgliedschaft" | "unternehmen";
  };
  author: {
    name: string;
    slug: string;
    image: {
      alt: string | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
        } | null;
      } | null;
    } | null;
  };
}>;

// Source: lib/sanity/queries.ts
// Variable: NEUESTE_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)]    | order(publishedAt desc) [0...$anzahl] {  _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  mainImage{alt, asset->{_id, url, metadata{lqip, dimensions}}},  category->{title, "slug": slug.current, audience},  author->{name, "slug": slug.current, image{alt, asset->{_id, url, metadata{lqip}}}}}
export type NEUESTE_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  mainImage: {
    alt: string | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  category: {
    title: string;
    slug: string;
    audience: "clubbetrieb" | "einsteiger" | "gaeste" | "mitgliedschaft" | "unternehmen";
  };
  author: {
    name: string;
    slug: string;
    image: {
      alt: string | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
        } | null;
      } | null;
    } | null;
  };
}>;

// Source: lib/sanity/queries.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    body,    mainImage{alt, caption, asset->{_id, url, metadata{lqip, dimensions}}},    category->{title, "slug": slug.current, description, audience},    author->{      name,      "slug": slug.current,      role,      bio,      linkedin,      image{alt, asset->{_id, url, metadata{lqip, dimensions}}}    },    related[]->{  _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  mainImage{alt, asset->{_id, url, metadata{lqip, dimensions}}},  category->{title, "slug": slug.current, audience},  author->{name, "slug": slug.current, image{alt, asset->{_id, url, metadata{lqip}}}}},    seo{title, description, noindex}  }
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  body: BlockContent;
  mainImage: {
    alt: string | null;
    caption: string | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  category: {
    title: string;
    slug: string;
    description: string;
    audience: "clubbetrieb" | "einsteiger" | "gaeste" | "mitgliedschaft" | "unternehmen";
  };
  author: {
    name: string;
    slug: string;
    role: string;
    bio: string;
    linkedin: string | null;
    image: {
      alt: string | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
  };
  related: Array<{
    _id: string;
    title: string;
    slug: string;
    excerpt: string;
    publishedAt: string;
    mainImage: {
      alt: string | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
    category: {
      title: string;
      slug: string;
      audience: "clubbetrieb" | "einsteiger" | "gaeste" | "mitgliedschaft" | "unternehmen";
    };
    author: {
      name: string;
      slug: string;
      image: {
        alt: string | null;
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    };
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    noindex: boolean | null;
  } | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: CATEGORIES_WITH_COUNT_QUERY
// Query: *[_type == "category"] | order(order asc, title asc) {    _id,    title,    "slug": slug.current,    description,    audience,    order,    "anzahl": count(*[_type == "post" && defined(slug.current) && references(^._id)])  }
export type CATEGORIES_WITH_COUNT_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string;
  audience: "clubbetrieb" | "einsteiger" | "gaeste" | "mitgliedschaft" | "unternehmen";
  order: number | null;
  anzahl: number;
}>;

// Source: lib/sanity/queries.ts
// Variable: AUTHOR_BY_SLUG_QUERY
// Query: *[_type == "author" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    role,    bio,    linkedin,    image{alt, asset->{_id, url, metadata{lqip, dimensions}}},    "artikel": *[_type == "post" && author._ref == ^._id && defined(slug.current)]      | order(publishedAt desc) {  _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  mainImage{alt, asset->{_id, url, metadata{lqip, dimensions}}},  category->{title, "slug": slug.current, audience},  author->{name, "slug": slug.current, image{alt, asset->{_id, url, metadata{lqip}}}}}  }
export type AUTHOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  role: string;
  bio: string;
  linkedin: string | null;
  image: {
    alt: string | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
  } | null;
  artikel: Array<{
    _id: string;
    title: string;
    slug: string;
    excerpt: string;
    publishedAt: string;
    mainImage: {
      alt: string | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    } | null;
    category: {
      title: string;
      slug: string;
      audience: "clubbetrieb" | "einsteiger" | "gaeste" | "mitgliedschaft" | "unternehmen";
    };
    author: {
      name: string;
      slug: string;
      image: {
        alt: string | null;
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    };
  }>;
} | null;

// Source: lib/sanity/queries.ts
// Variable: FAQS_BY_TOPIC_QUERY
// Query: *[_type == "faq" && topic == $topic] | order(order asc, question asc) {    _id,    question,    answer,    topic,    order  }
export type FAQS_BY_TOPIC_QUERY_RESULT = Array<{
  _id: string;
  question: string;
  answer: SimpleBlockContent;
  topic: "allgemein" | "clubprozesse" | "pakete" | "plattform" | "wachstum";
  order: number | null;
}>;

// Source: lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    phone,    email,    responseNote,    bookingUrl,    linkedin,    instagram,    defaultSeo{title, description, ogImage{alt, asset->{_id, url}}}  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      phone: null;
      email: null;
      responseNote: null;
      bookingUrl: null;
      linkedin: null;
      instagram: null;
      defaultSeo: null;
    }
  | {
      phone: null;
      email: null;
      responseNote: null;
      bookingUrl: null;
      linkedin: string | null;
      instagram: null;
      defaultSeo: null;
    }
  | {
      phone: string;
      email: string;
      responseNote: string | null;
      bookingUrl: string | null;
      linkedin: string | null;
      instagram: string | null;
      defaultSeo: {
        title: string | null;
        description: string | null;
        ogImage: {
          alt: string | null;
          asset: {
            _id: string;
            url: string;
          } | null;
        } | null;
      } | null;
    }
  | null;

// Source: lib/sanity/slugs.ts
// Variable: SLUGS_QUERY
// Query: {  "artikel": *[_type == "post" && defined(slug.current)].slug.current,  "rubriken": *[_type == "category" && defined(slug.current)].slug.current}
export type SLUGS_QUERY_RESULT = {
  artikel: Array<string>;
  rubriken: Array<string>;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "post" && defined(slug.current) && (!defined($rubrik) || category->slug.current == $rubrik)]\n    | order(publishedAt desc) {\n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  mainImage{alt, asset->{_id, url, metadata{lqip, dimensions}}},\n  category->{title, "slug": slug.current, audience},\n  author->{name, "slug": slug.current, image{alt, asset->{_id, url, metadata{lqip}}}}\n}\n': POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]\n    | order(publishedAt desc) [0...$anzahl] {\n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  mainImage{alt, asset->{_id, url, metadata{lqip, dimensions}}},\n  category->{title, "slug": slug.current, audience},\n  author->{name, "slug": slug.current, image{alt, asset->{_id, url, metadata{lqip}}}}\n}\n': NEUESTE_POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    publishedAt,\n    body,\n    mainImage{alt, caption, asset->{_id, url, metadata{lqip, dimensions}}},\n    category->{title, "slug": slug.current, description, audience},\n    author->{\n      name,\n      "slug": slug.current,\n      role,\n      bio,\n      linkedin,\n      image{alt, asset->{_id, url, metadata{lqip, dimensions}}}\n    },\n    related[]->{\n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  mainImage{alt, asset->{_id, url, metadata{lqip, dimensions}}},\n  category->{title, "slug": slug.current, audience},\n  author->{name, "slug": slug.current, image{alt, asset->{_id, url, metadata{lqip}}}}\n},\n    seo{title, description, noindex}\n  }\n': POST_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "category"] | order(order asc, title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    audience,\n    order,\n    "anzahl": count(*[_type == "post" && defined(slug.current) && references(^._id)])\n  }\n': CATEGORIES_WITH_COUNT_QUERY_RESULT;
    '\n  *[_type == "author" && slug.current == $slug][0]{\n    _id,\n    name,\n    "slug": slug.current,\n    role,\n    bio,\n    linkedin,\n    image{alt, asset->{_id, url, metadata{lqip, dimensions}}},\n    "artikel": *[_type == "post" && author._ref == ^._id && defined(slug.current)]\n      | order(publishedAt desc) {\n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  mainImage{alt, asset->{_id, url, metadata{lqip, dimensions}}},\n  category->{title, "slug": slug.current, audience},\n  author->{name, "slug": slug.current, image{alt, asset->{_id, url, metadata{lqip}}}}\n}\n  }\n': AUTHOR_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "faq" && topic == $topic] | order(order asc, question asc) {\n    _id,\n    question,\n    answer,\n    topic,\n    order\n  }\n': FAQS_BY_TOPIC_QUERY_RESULT;
    '\n  *[_id == "siteSettings"][0]{\n    phone,\n    email,\n    responseNote,\n    bookingUrl,\n    linkedin,\n    instagram,\n    defaultSeo{title, description, ogImage{alt, asset->{_id, url}}}\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '{\n  "artikel": *[_type == "post" && defined(slug.current)].slug.current,\n  "rubriken": *[_type == "category" && defined(slug.current)].slug.current\n}': SLUGS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
